server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microservices
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  data:
    jpa:
      repositories:
        enabled: true

  application:
    name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-41558616.okta.com/oauth2/default
    audience: api://default
